/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import HeadlessWorkManager from 'react-native-headless-work-manager';

const TASK_KEY = 'ExampleTask';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    workInfos: null,
  };

  async componentDidMount() {
    try {
      const { workerId } = await HeadlessWorkManager.enqueue({
        workRequestType: HeadlessWorkManager.PERIODIC_WORK_REQUEST,
        taskKey: TASK_KEY,
        isUnique: true,
        existingWorkPolicy: HeadlessWorkManager.REPLACE,
        timeout: 1000,
        interval: 15,
        timeUnit: HeadlessWorkManager.MINUTES,
        data: {
          foo: 'bar',
        },
      });
      this.setState({ status: `worker enqueued with ID ${workerId}, check logs for task output` });

      const workInfos = await HeadlessWorkManager.getWorkInfosForUniqueWork(TASK_KEY);
      this.setState({ workInfos });
    } catch(err) {
      this.setState({ status: `error: ${err.message}` });
    }
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆WorkManager example☆</Text>
        <Text style={styles.instructions}>Status: {this.state.status}</Text>
        <Text style={styles.welcome}>Work info</Text>
        <Text style={styles.instructions}>{JSON.stringify(this.state.workInfos)}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
